// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfuQGKcpqIXm4F6Bq4F1yk-snOI3ymukI',
    appId: '1:1022080912311:web:6c7d9898c6024c3f53f632',
    messagingSenderId: '1022080912311',
    projectId: 'contact-app-be62f',
    authDomain: 'contact-app-be62f.firebaseapp.com',
    storageBucket: 'contact-app-be62f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3z6hvRfkVBGhiP_uUrbNaZ9PUz30ArFQ',
    appId: '1:1022080912311:android:44139ef9e574f27153f632',
    messagingSenderId: '1022080912311',
    projectId: 'contact-app-be62f',
    storageBucket: 'contact-app-be62f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-EITptus6Diou-NY2WYxv-X_Oxri5mo',
    appId: '1:1022080912311:ios:8e29306fedeaeb0e53f632',
    messagingSenderId: '1022080912311',
    projectId: 'contact-app-be62f',
    storageBucket: 'contact-app-be62f.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB-EITptus6Diou-NY2WYxv-X_Oxri5mo',
    appId: '1:1022080912311:ios:8e29306fedeaeb0e53f632',
    messagingSenderId: '1022080912311',
    projectId: 'contact-app-be62f',
    storageBucket: 'contact-app-be62f.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfuQGKcpqIXm4F6Bq4F1yk-snOI3ymukI',
    appId: '1:1022080912311:web:448d0547ba79590653f632',
    messagingSenderId: '1022080912311',
    projectId: 'contact-app-be62f',
    authDomain: 'contact-app-be62f.firebaseapp.com',
    storageBucket: 'contact-app-be62f.firebasestorage.app',
  );
}
